<?php

use App\Factors;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $connections = [
            Factors::Agility->value => [
                Factors::Strength->value,
                Factors::Motor->value,
                Factors::Posture->value,
                Factors::PhysicalTraining->value,
                Factors::ActivitiesTimeSpent->value,
                Factors::Sitting->value,
                Factors::BodySat->value,
                Factors::Health->value,
                Factors::BodySympt->value,
                Factors::Headache->value,
                Factors::Stress->value,
                Factors::Work->value,
            ],
            Factors::Strength->value => [
                Factors::Agility->value,
                Factors::Strength->value,
                Factors::Balance->value,
                Factors::Posture->value,
                Factors::PhysicalTraining->value,
                Factors::ActivitiesTimeSpent->value,
                Factors::Sitting->value,
                Factors::BodySat->value,
                Factors::BodySympt->value,
                Factors::Headache->value,
                Factors::FoodEnergyBalance->value,
                Factors::FoodSweets->value,
                Factors::Media->value,
            ],
            Factors::Balance->value => [
                Factors::Agility->value,
                Factors::Motor->value,
                Factors::Posture->value,
                Factors::PhysicalTraining->value,
                Factors::Sitting->value,
            ],
            Factors::Motor->value => [
                Factors::Strength->value,
                Factors::PhysicalTraining->value,
                Factors::ActivitiesTimeSpent->value,
                Factors::Sitting->value,
                Factors::BodySat->value,
                Factors::Health->value,
                Factors::BodySympt->value,
                Factors::Alcohol->value,
            ],
            Factors::Posture->value => [
                Factors::Agility->value,
                Factors::Strength->value,
                Factors::Balance->value,
                Factors::Motor->value,
                Factors::PhysicalTraining->value,
                Factors::ActivitiesTimeSpent->value,
                Factors::Sitting->value,
                Factors::BodySat->value,
                Factors::Health->value,
                Factors::BodySympt->value,
                Factors::Headache->value,
                Factors::Sleep->value,
            ],
            Factors::Weight->value => [
                Factors::PhysicalTraining->value,
                Factors::ActivitiesTimeSpent->value,
                Factors::Sitting->value,
                Factors::BodySat->value,
                Factors::Health->value,
                Factors::Stomachache->value,
                Factors::Headache->value,
                Factors::Sleep->value,
                Factors::Stress->value,
                Factors::Snuffing->value,
                Factors::Smoking->value,
                Factors::Alcohol->value,
                Factors::FoodHabits->value,
                Factors::FoodEnergyBalance->value,
                Factors::FoodSweets->value,
                Factors::FoodFluid->value,
                Factors::FoodEnergyDrinks->value,
            ],
            Factors::Fitness->value => [
                Factors::PhysicalTraining->value,
                Factors::Sitting->value,
                Factors::Smoking->value,
                Factors::Snuffing->value,
                Factors::FoodEnergyBalance->value,
                Factors::Work->value,
            ],
            Factors::PhysicalTraining->value => [
                Factors::Agility->value,
                Factors::Strength->value,
                Factors::Balance->value,
                Factors::Motor->value,
                Factors::Posture->value,
                Factors::ActivitiesTimeSpent->value,
                Factors::Sitting->value,
                Factors::BodySat->value,
                Factors::Health->value,
                Factors::BodySympt->value,
                Factors::Relaxed->value,
                Factors::Headache->value,
                Factors::Sleep->value,
                Factors::Stress->value,
                Factors::Smoking->value,
                Factors::Snuffing->value,
                Factors::Alcohol->value,
                Factors::FoodHabits->value,
                Factors::FoodEnergyBalance->value,
                Factors::FoodFluid->value,
                Factors::FoodEnergyDrinks->value,
                Factors::Freetime->value,
                Factors::Media->value,
            ],
            Factors::ActivitiesTimeSpent->value => [
                Factors::Motor->value,
                Factors::Posture->value,
                Factors::PhysicalTraining->value,
                Factors::Sitting->value,
                Factors::Health->value,
                Factors::BodySympt->value,
                Factors::Relaxed->value,
                Factors::Stomachache->value,
                Factors::Headache->value,
                Factors::Sleep->value,
                Factors::Stress->value,
                Factors::Alcohol->value,
                Factors::FoodHabits->value,
                Factors::FoodEnergyBalance->value,
                Factors::Freetime->value,
                Factors::Media->value,
                Factors::Work->value,
            ],
            Factors::Sitting->value => [
                Factors::Agility->value,
                Factors::Strength->value,
                Factors::Balance->value,
                Factors::Motor->value,
                Factors::Posture->value,
                Factors::PhysicalTraining->value,
                Factors::ActivitiesTimeSpent->value,
                Factors::BodySat->value,
                Factors::Health->value,
                Factors::BodySympt->value,
                Factors::Relaxed->value,
                Factors::Stomachache->value,
                Factors::Headache->value,
                Factors::Sleep->value,
                Factors::Stress->value,
                Factors::Alcohol->value,
                Factors::FoodHabits->value,
                Factors::FoodEnergyBalance->value,
                Factors::FoodSweets->value,
                Factors::Freetime->value,
                Factors::Media->value,
                Factors::Work->value,
            ],
            Factors::BodySat->value => [
                Factors::Agility->value,
                Factors::Strength->value,
                Factors::Balance->value,
                Factors::Motor->value,
                Factors::Posture->value,
                Factors::PhysicalTraining->value,
                Factors::ActivitiesTimeSpent->value,
                Factors::Sitting->value,
                Factors::Health->value,
                Factors::Relaxed->value,
                Factors::Stomachache->value,
                Factors::Headache->value,
                Factors::Sleep->value,
                Factors::Smoking->value,
                Factors::Snuffing->value,
                Factors::Alcohol->value,
                Factors::FoodHabits->value,
                Factors::FoodEnergyBalance->value,
                Factors::FoodSweets->value,
                Factors::Media->value,
            ],
            Factors::Health->value => [
                Factors::Agility->value,
                Factors::Strength->value,
                Factors::Balance->value,
                Factors::Posture->value,
                Factors::PhysicalTraining->value,
                Factors::ActivitiesTimeSpent->value,
                Factors::Sitting->value,
                Factors::BodySat->value,
                Factors::BodySympt->value,
                Factors::Relaxed->value,
                Factors::Stomachache->value,
                Factors::Headache->value,
                Factors::Sleep->value,
                Factors::Stress->value,
                Factors::Smoking->value,
                Factors::Snuffing->value,
                Factors::Alcohol->value,
                Factors::FoodHabits->value,
                Factors::FoodEnergyBalance->value,
                Factors::FoodEnergyDrinks->value,
                Factors::Freetime->value,
                Factors::Media->value,
                Factors::Friends->value,
            ],
            Factors::BodySympt->value => [
                Factors::Agility->value,
                Factors::Strength->value,
                Factors::Posture->value,
                Factors::PhysicalTraining->value,
                Factors::ActivitiesTimeSpent->value,
                Factors::Sitting->value,
                Factors::BodySat->value,
                Factors::Health->value,
                Factors::Relaxed->value,
                Factors::Headache->value,
                Factors::Sleep->value,
                Factors::Stress->value,
                Factors::Smoking->value,
                Factors::Snuffing->value,
                Factors::Alcohol->value,
                Factors::FoodHabits->value,
                Factors::Media->value,
                Factors::Work->value,
            ],
            Factors::Relaxed->value => [
                Factors::PhysicalTraining->value,
                Factors::ActivitiesTimeSpent->value,
                Factors::Sitting->value,
                Factors::Health->value,
                Factors::BodySympt->value,
                Factors::Stomachache->value,
                Factors::Headache->value,
                Factors::Sleep->value,
                Factors::Stress->value,
                Factors::Smoking->value,
                Factors::Snuffing->value,
                Factors::Alcohol->value,
                Factors::FoodHabits->value,
                Factors::FoodEnergyBalance->value,
                Factors::FoodFluid->value,
                Factors::Media->value,
                Factors::Work->value,
            ],
            Factors::Stomachache->value => [
                Factors::PhysicalTraining->value,
                Factors::ActivitiesTimeSpent->value,
                Factors::Sitting->value,
                Factors::Health->value,
                Factors::BodySympt->value,
                Factors::Relaxed->value,
                Factors::Sleep->value,
                Factors::Stress->value,
                Factors::Smoking->value,
                Factors::Snuffing->value,
                Factors::Alcohol->value,
                Factors::FoodHabits->value,
                Factors::FoodEnergyBalance->value,
                Factors::Media->value,
            ],
            Factors::Headache->value => [
                Factors::FoodEnergyBalance->value,
                Factors::FoodFruit->value,
                Factors::Media->value,
                Factors::Work->value,
            ],
            Factors::Sleep->value => [
                Factors::PhysicalTraining->value,
                Factors::ActivitiesTimeSpent->value,
                Factors::Sitting->value,
                Factors::Health->value,
                Factors::BodySympt->value,
                Factors::Relaxed->value,
                Factors::Stomachache->value,
                Factors::Headache->value,
                Factors::Stress->value,
                Factors::Smoking->value,
                Factors::Snuffing->value,
                Factors::Alcohol->value,
                Factors::FoodHabits->value,
                Factors::FoodEnergyBalance->value,
                Factors::FoodFluid->value,
                Factors::FoodEnergyDrinks->value,
                Factors::Freetime->value,
                Factors::Media->value,
                Factors::Work->value,
            ],
            Factors::Stress->value => [
                Factors::PhysicalTraining->value,
                Factors::ActivitiesTimeSpent->value,
                Factors::Sitting->value,
                Factors::BodySat->value,
                Factors::Health->value,
                Factors::BodySympt->value,
                Factors::Relaxed->value,
                Factors::Stomachache->value,
                Factors::Headache->value,
                Factors::Sleep->value,
                Factors::Smoking->value,
                Factors::Snuffing->value,
                Factors::Alcohol->value,
                Factors::FoodHabits->value,
                Factors::FoodEnergyBalance->value,
                Factors::FoodFluid->value,
                Factors::FoodEnergyDrinks->value,
                Factors::Freetime->value,
                Factors::Media->value,
                Factors::Friends->value,
                Factors::Work->value,
            ],
            Factors::Smoking->value => [
                Factors::PhysicalTraining->value,
                Factors::Health->value,
                Factors::BodySympt->value,
                Factors::Relaxed->value,
                Factors::Stomachache->value,
                Factors::Headache->value,
                Factors::Sleep->value,
                Factors::Stress->value,
                Factors::FoodEnergyBalance->value,
                Factors::Work->value,
            ],
            Factors::Snuffing->value => [],
            Factors::Alcohol->value => [
                Factors::BodySat->value,
                Factors::Sleep->value,
                Factors::FoodEnergyBalance->value,
                Factors::Work->value,
            ],
            Factors::FoodHabits->value => [
                Factors::Health->value,
                Factors::Stomachache->value,
                Factors::Headache->value,
                Factors::Sleep->value,
                Factors::Stress->value,
                Factors::FoodEnergyBalance->value,
                Factors::Freetime->value,
                Factors::Media->value,
                Factors::Work->value,
            ],
            Factors::FoodEnergyBalance->value => [
                Factors::PhysicalTraining->value,
                Factors::ActivitiesTimeSpent->value,
                Factors::Sitting->value,
                Factors::BodySat->value,
                Factors::Health->value,
                Factors::Relaxed->value,
                Factors::Stomachache->value,
                Factors::Headache->value,
                Factors::Sleep->value,
                Factors::Stress->value,
                Factors::Smoking->value,
                Factors::Snuffing->value,
                Factors::FoodHabits->value,
                Factors::FoodSweets->value,
                Factors::Freetime->value,
                Factors::Media->value,
            ],
            Factors::FoodFruit->value => [
            ],
            Factors::FoodSweets->value => [
                Factors::BodySat->value,
                Factors::Health->value,
                Factors::Relaxed->value,
                Factors::Stomachache->value,
                Factors::Sleep->value,
                Factors::FoodEnergyBalance->value,
            ],
            Factors::FoodFluid->value => [
                Factors::Health->value,
                Factors::Stomachache->value,
                Factors::Headache->value,
                Factors::Sleep->value,
                Factors::Stress->value,
            ],
            Factors::FoodEnergyDrinks->value => [
                Factors::BodySat->value,
                Factors::Sleep->value,
                Factors::FoodEnergyBalance->value,
                Factors::Work->value,
            ],
            Factors::Freetime->value => [
                Factors::PhysicalTraining->value,
                Factors::Sitting->value,
                Factors::BodySat->value,
                Factors::Health->value,
                Factors::BodySympt->value,
                Factors::Relaxed->value,
                Factors::Headache->value,
                Factors::Sleep->value,
                Factors::Stress->value,
                Factors::Smoking->value,
                Factors::Snuffing->value,
                Factors::Alcohol->value,
                Factors::FoodHabits->value,
                Factors::FoodEnergyBalance->value,
            ],
            Factors::Media->value => [
                Factors::Sitting->value,
                Factors::BodySat->value,
                Factors::BodySympt->value,
                Factors::Relaxed->value,
                Factors::Stomachache->value,
                Factors::Headache->value,
                Factors::Sleep->value,
                Factors::Alcohol->value,
                Factors::FoodHabits->value,
            ],
            Factors::Friends->value => [
                Factors::Sitting->value,
                Factors::BodySat->value,
                Factors::Health->value,
                Factors::Stomachache->value,
                Factors::Headache->value,
                Factors::Sleep->value,
                Factors::Stress->value,
                Factors::Smoking->value,
                Factors::Snuffing->value,
                Factors::Alcohol->value,
                Factors::Media->value,
                Factors::Work->value,
            ],
            Factors::Work->value => [
                Factors::Headache->value,
                Factors::Alcohol->value,
                Factors::Media->value,
            ],
        ];

        foreach ($connections as $factor => $factors) {
            foreach ($factors as $secondFactor) {
                DB::table('category_connections')->insert([
                    'category_id' => $factor,
                    'affected_by_id' => $secondFactor,
                ]);
            }
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        DB::table('category_connections')->truncate();
    }
};
